apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: football-ingress
  namespace: league
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: football-nginx
  rules:
  - host: example.com
    http:
      paths:
      - path: /football
        pathType: Prefix
        backend:
          service:
            name: football-svc
            port:
              number: 80