apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: test-job
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: busybox:1.23
        name: test-job
        command: ['sh', '-c', 'date; echo "Hello from AlexM"']
        resources: {}
      restartPolicy: OnFailure
status: {}
