apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: pm
  namespace: football
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: pm-role
  namespace: football
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: pm-bind
  namespace: football
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pm-role
subjects:
- kind: ServiceAccount
  name: pm
  namespace: football
